[llama_wrangler_index]
definition = index=llama_wrangler
iseval = 0

[llama_wrangler_requests]
definition = `llama_wrangler_index` sourcetype=llama_wrangler:request
iseval = 0

[llama_wrangler_responses]
definition = `llama_wrangler_index` sourcetype=llama_wrangler:response
iseval = 0

[llama_wrangler_health]
definition = `llama_wrangler_index` sourcetype=llama_wrangler:node_health
iseval = 0
