[eventtype=llama_wrangler_requests]
llm = enabled
ai = enabled

[eventtype=llama_wrangler_responses]
llm = enabled
ai = enabled

[eventtype=llama_wrangler_errors]
llm = enabled
ai = enabled
error = enabled
